# -*- coding: utf-8 -*-
"""inweh treasure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BTR67T_Ot7qK-EG-jrkmannJAFE0kgI9
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/epidemiology.csv')

print(df.shape)

df.head()